paths:
  /api/products/:
    get: # productsRouter.get('/', getProducts)
      summary: Obtener todos los productos 
      tags: 
        - Product
      responses:
        '200':
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '500':
          description: Error al obtener los productos
    post: # productsRouter.post('/', passport.authenticate('jwt', { session: false}), createProduct)
      summary: Crear un nuevo producto
      tags:
        - Product
      parameters:
        - name: body
          in: body
          required: true
          chema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        '201':
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Products'
        '500':
          description: Error al crear el producto
  /api/products/{id}:
    get: # productsRouter.get('/:pid', getProduct)
     summary: Obtener un producto 
      tags: 
        - Product
      responses:
        '200':
          description: Producto obtenido correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '500':
          description: Error al obtener usuarios
    put: # productsRouter.put('/:pid', passport.authenticate('jwt', { session: false}), updateProduct)
      summary: Actualizar un producto 
      tags: 
        - Product
      responses:
        '200':
          description: Productos actualizado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '500':
          description: Error al actualizar el producto
    delete: # productsRouter.delete('/:pid', passport.authenticate('jwt', { session: false}), deleteProduct)
      summary: Eliminar un producto 
      tags: 
        - Product
      responses:
        '200':
          description: Producto eliminado correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '500':
          description: Error al eliminar el producto

components:
    schemas:
     Product:
        type: object
        properties:
          product_Id:
            type: ObjectId
            description: Id autogerado por MongoDB
          title:
            type: String
            description: Nombre del producto
          description:
            type: String
            description: Descripción del producto
          category:
            type: String
            description: categoría del producto
          status:
            type: Boolean
            description: Estado del producto
          stock:
            type: Number
            description: Cantidad de producto en stock
          code:
            type: String
            description: Código de producto en BD
          price:
            type: Number
            description: Precio comercial de producto
          thumbnail:
            type: Default
            description: Imagen de producto
        example:
          Product_id: ObjectId('1321ewew22')
          Title: Lentejas
          description: Sabrosas y baratas
          category: Comida
          status: 'True'
          stock: '25'
          code: 'ltn45d'
          price: '15000'
          thumbnail: 'http://leguminosa/lenteja?:mvn100'

        



